cmd_vel_selector:
  ros__parameters:
    output_topic: "/cmd_vel"

    # Beim Start ist keine Bewegungsquelle freigegeben.
    initial_source: "none"

    topics:
      webteleop: "/cmd_vel/webteleop"
      tasks: "/cmd_vel/tasks"
